###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

services:
  actual_server:
    image: actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - ./actual-data:/data
      - ./certs:/certs # Monta la cartella dei certificati
    environment:
      - ACTUAL_HTTPS_KEY=/certs/actual.key
      - ACTUAL_HTTPS_CERT=/certs/actual.crt
    restart: unless-stopped
